version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=isntgram
      - POSTGRES_USER=blackmule
      - POSTGRES_PASSWORD=strsec
  backend:
    user: 1000:1000
    container_name: backend
    build: ./backend
    command: /scripts.sh
    volumes:
      - .:/code
      - django-static:/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  django-static:
  db: {}