version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    #environment:
    #  - POSTGRES_DB=postgres
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_PASSWORD=postgres
    #  POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - django-nginx
  backend:
    container_name: backend
    build: ./backend
    command: /scripts.sh
    volumes:
      - .:/code
      - django-static:/backend/static
    networks:
      - django-nginx
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend:ro
    networks:
      - django-nginx
    depends_on:
      - backend
      - db
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - django-nginx
volumes:
  django-static:
  db: {}
networks:
  django-nginx:
    driver: bridge
  